### PR TITLE
Expose NSWindow Callbacks for Enhanced Window Handling

### PR DESCRIPTION
**Pull request by ganeshrvel**
This PR proposes exposing several NSWindow event callbacks, such as `onWindowDidBecomeMain`, `onWindowDidResignMain`, `onWindowDidBecomeKey`, `onWindowDidResignKey`, `onWindowDidChangeScreen`, `onWindowDidMove`, and `onWindowDidResize`, to allow developers to leverage and customize window behavior better.

## Pre-launch Checklist

- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

### CODE REVIEW

**Comment by GroovinChip** [comment]
@Adrian-Samoticha what are your thoughts on this? Do we want to route more of MWU through MUI, or would you rather folks use MWU directly?

**Comment by Adrian-Samoticha** [comment]
> @Adrian-Samoticha what are your thoughts on this? Do we want to route more of MWU through MUI, or would you rather folks use MWU directly?

Frankly, I do like this proposal. I think since we’re already routing MWU calls through MUI it probably doesn’t hurt to expand on that. However, I’d argue that we should go all the way and expose *all* `NSWindowDelegate` callbacks in that case. 

Furthermore, I’d argue that using `VoidCallback` here isn’t ideal, since that means that you can only define a single function for each callback. I’d suggest we instead define a sort of “window event stream” which emits an enum corresponding to each `NSWindowDelegate` method whenever an event is triggered.

**Comment by GroovinChip** [comment]
I agree @Adrian-Samoticha. @ganeshrvel, can you please make the proposed changes?

**Comment by GroovinChip** [comment]
@ganeshrvel I am closing this due to inactivity. Please feel free to reopen when you are ready to make the requested changes.

**Pull request closed without merging**
