### PR TITLE
Fix EnumProperty test.

### PR DESCRIPTION
**Pull request by bernaferrari**
I'm changing `EnumProperty` to require an `Enum` and your test still uses a class. In Flutter, it went to DiagnosticsProperty, which is what I'm doing here.

image

Related: https://github.com/flutter/flutter/pull/125016

### CODE REVIEW

**Comment by goderbauer** [comment]
@GroovinChip Can you take a look at this one? It is blocking some work in Flutter (https://github.com/flutter/flutter/pull/125016).

**Comment by GroovinChip** [comment]
> @GroovinChip Can you take a look at this one? It is blocking some work in Flutter (https://github.com/flutter/flutter/pull/125016).

Yes, thank you

**Comment by GroovinChip** [comment]
Looks like the Flutter 3.10 stuff needs to get merged first. I'll take care of it.

**Comment by GroovinChip** [comment]
@bernaferrari Can you please merge the latest from `dev` into your branch? It should resolve the failing checks.

**Pull request merged**
