### PR TITLE
Version 1.7.0: `MacosImageIcon` & sidebar updates

### LINKED ISSUE #275: Sidebar should support multiple sizes
According to [this page](https://developer.apple.com/design/human-interface-guidelines/components/navigation-and-search/sidebars#platform-considerations) of the Human Interface Guidelines, sidebars can have `small`, `medium`, and `large` sizes.

Apple's Mail and Notes app seem to use the `medium` size.

### LINKED ISSUE #276: `SidebarItem`s should have an optional trailing widget
As can be seen in Apple's Mail and Notes apps, sidebar items can have trailing content.

### LINKED ISSUE #277: New widget: `MacosImageIcon`
Should be identical to the `ImageIcon` from `flutter/widgets` but respect a `MacosIconThemeData` instead of an `IconThemeData`.

### PR DESCRIPTION
**Pull request by GroovinChip**
This PR includes version 1.7.0 of `macos_ui` with the following changes:
* New
  * `MacosImageIcon` widget. Identical to the `ImageIcon` from `flutter/widgets.dart` except it will obey a 
`MacosIconThemeData` instead of an `IconThemeData`
  * `SidebarItemSize` enum, which determines the height of sidebar items and the maximum size their `leading` widgets.
  * `SidebarItem` now accepts an optional `trailing` widget.
* Updated
  * `SidebarItems` now supports `SidebarItemSize` via the `itemSize` property, which defaults to 
`SidebarItemSize.medium`. The widget has been updated to manage the item's height, the maximum size of the item's 
leading widget, and the font size of the item's label widget according to the given `SidebarItemSize`.
  * The example app has been tweaked to use some icons from the SF Symbols 4 Beta via the new `MacosImageIcon` widget.

Closes #275, #276, and #277.

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files 
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

### CODE REVIEW

**Review by whiplashoo — APPROVED** [review]

**Comment by whiplashoo** [comment]
LGTM

**Comment by GroovinChip** [comment]
> LGTM

Looks like some tests are failing 👀

**Comment by whiplashoo** [comment]
Not sure why the datepicker test fails though?

**Comment by GroovinChip** [comment]
> Not sure why the datepicker test fails though?

I patched that in dev, not sure why it hasn't been brought over 🤔 try cherry-picking that commit? I'm afk.

**Comment by GroovinChip** [comment]
This one https://github.com/GroovinChip/macos_ui/commit/5687498c7826a223f0758da46a92c1aadf0c5c72

**Comment by whiplashoo** [comment]
The failing test was not affected by that commit.

I changed it to look for a higher number (21 instead of 10) to avoid collisions with months, and to look for 22 if it's ran on the 22th. 😑

**Pull request merged**
