### PR TITLE
fix: SearchField overlay actions are not performed

### LINKED ISSUE #348: MacosSearchField does not execute the onResultSelected function
**Description**
When an item from the MacosSearchField is selected, the `onResultSelected` function of the field itself and the `onSelected` function of the selected `SearchResultItem` is not called.

**Steps To Reproduce**
1. Go to the Fields page of the example project
2. Type something in one of the search fields
3. Select one of the options
4. This should print the selected SearchResultItem to the console. This does not happen.

After testing, I found out that removing the lines 245 and 246 of the `search_field.dart` file resolves the error:

```dart
} else {
   _overlayEntry.remove();
```

But I am not sure if this breaks some other intended behavior.

### PR DESCRIPTION
**Pull request by FelixMethe**
See #348 for more details

## Pre-launch Checklist

- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

### CODE REVIEW

**Comment by GroovinChip** [comment]
OK @FelixMethe so I know you're probably looking at this going "WTF is this guy doing to my PR???" 😅 well, the answer is that I'm trying to automate dealing with cases where `flutter pub get` results in an updated lockfile, to commit and push it so that I don't have to ask the PR author to do it. It's a hard thing to test, obviously, so I'm using your PR as a guinea pig 😅 

If I can't get it to work soon, I may just have to try and have the bot post a comment tagging the PR author and asking to run pub get.

**Comment by GroovinChip** [comment]
OK THIS IS DRIVING ME NUTS so I'm gonna ditch this effort and just ask you to please run `flutter pub get` and push the changes. I'm really sorry about mucking up your git history - feel free to reset hard and get rid of it all.

**Comment by GroovinChip** [comment]
@FelixMethe I've pulled down your branch to test the changes, and I'm noticing that when a search suggestion is clicked, it doesn't go away, which I think is the expected behavior. Do you mind adding that behavior, please?

**Comment by FelixMethe** [comment]
@GroovinChip when I test the SearchFields of the example app, the overlay disappears after clicking on a selection.
Did you mean something else?
Is there away to define a SearchField that breaks this behavior?

**Comment by GroovinChip** [comment]
> @GroovinChip when I test the SearchFields of the example app, the overlay disappears after clicking on a selection. Did you mean something else? Is there away to define a SearchField that breaks this behavior?

Yeah, for me the overlay does not disappear in the example app. And this is when I run it on your branch. 

In order to define breaking behavior, We should have a test where the passing condition is that the overlay does disappear after clicking on a selection. If the test fails, we will know the feature isn't working correctly.

**Comment by FelixMethe** [comment]
@GroovinChip the test passes. Could you check if I implemented the test correctly? I am not confident in my testing ability 😅

**Comment by GroovinChip** [comment]
> @GroovinChip the test passes. Could you check if I implemented the test correctly? I am not confident in my testing ability 😅

Looks good to me

**Review by GroovinChip — APPROVED** [review]
LGTM 🎉

**Pull request merged**
