### PR TITLE
Scrollbar overhaul & more

### LINKED ISSUE #343: The example app does no longer show the bottom ListTile of the sidebar
**Description**

**Steps To Reproduce**

1.  git clone https://github.com/GroovinChip/macos_ui.git
2. git checkout stable
3. Build and start the example app
4. The bottom MacosListTile is not showing (see screenshot)

**Expected behavior**

The bottom MacosListTile of a MacosWindow sidebar should be visible.

** Flutter doctor **
```
 flutter doctor -v
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.6 21G115 darwin-arm64, locale de-DE)
    • Flutter version 3.7.0 on channel stable at /Users/aschilken/fvm/versions/3.7.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (13 days ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/aschilken/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone SE (mobile) • A83467CE-B7D9-4205-BCB5-D13AB68E6587 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Screenshots**

screenshot example app

### PR DESCRIPTION
**Pull request by GroovinChip**
This PR contains the following breaking changes:
* `MacosScrollbar` has been completely overhauled and now  [more closely] resembles the native macOS scrollbar in appearance and behavior. Previously, it wrapped the material scrollbar, and now creates a custom scrollbar that extends
  `RawScrollbar`. This resulted in the removal of several material-based properties for the scrollbar, and
  `ContentArea.builder` is once again a `ScrollableWidgetBuilder`.
* Removes material-based scrollbar properties from `MacosScrollbarThemeData`

Other changes:
* Updates `dart_code_metrics` and related rules
* Moved `scrollbar.dart` from `/indicators` to `/layout`, as it is a more appropriate location.

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files 
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

### CODE REVIEW

**Comment by GroovinChip** [comment]
@whiplashoo I'd like your review on this one, if you have the time.

**Review by whiplashoo — COMMENTED** [review]
The new scrollbar looks really nice, almost identical to macOS one. 

My only note: shouldn't it also appear when hovering over it? 

On macOS, after scrolling and while the scrollbar is visible, hovering over any point of the track, activates the scrollbar's animation and thickness effect:

https://user-images.githubusercontent.com/9117427/217931104-46eb59a3-c6ca-4c73-831e-7b1798aa8795.mov

There is a `handleHover` method we can override in `ScrollBar`.

**Comment by GroovinChip** [comment]
> The new scrollbar looks really nice, almost identical to macOS one. 
> 
> 
> 
> My only note: shouldn't it also appear when hovering over it? 
> 
> 
> 
> On macOS, after scrolling and while the scrollbar is visible, hovering over any point of the track, activates the scrollbar's animation and thickness effect:
> 
> 
> 
> https://user-images.githubusercontent.com/9117427/217931104-46eb59a3-c6ca-4c73-831e-7b1798aa8795.mov
> 
> 
> 
> There is a `handleHover` method we can override in `ScrollBar`.
> 
> 

Thanks! Yes, the scrollbar should absolutely show the track on hover. I meant to add that but I forgot. I also don't think I knew about the `handleHover` override. I'll try and implement that tonight.

One thing, though, and I can't check on this now as I'm AFK, but I believe that the behavior of the scrollbar differs slightly between  Apple's apps (classic).

**Comment by whiplashoo** [comment]
Yes, sure. I can see that on Finder, the inner scrollbar doesn't have that hover effect, for example, but it's there on Safari, Notes, and Reminders 🤷‍♂️

**Comment by GroovinChip** [comment]
@whiplashoo Alright then, I'm inclined to say that the default behavior should follow how the majority of apps behave. I'll work on adding this.

As an aside, if you have any tips on testing the scrollbar, I'm all ears. I've been banging my head against the wall for like a week about that!

**Comment by GroovinChip** [comment]
Alrighty @whiplashoo, hover effect has been implemented!

**Review by whiplashoo — APPROVED** [review]
Yes, that looks and works great! 

Can't think anything on the testing side, though. Since the scrollbar is a wrapper around `RawScrollbar`, I am not sure if there is a lot to test, apart from the visual stuff.

**Comment by GroovinChip** [comment]
> Yes, that looks and works great! 
> 
> 
> 
> Can't think anything on the testing side, though. Since the scrollbar is a wrapper around `RawScrollbar`, I am not sure if there is a lot to test, apart from the visual stuff.

Amazing!

Edit: actually @whiplashoo the reason I want to test the scrollbar is I'm trying to add macos_ui to Flutter's customer testing and having tests will help alert us if something breaks RawScrollbar

Thanks so much for the review!

**Comment by GroovinChip** [comment]
The DCM check failing is driving me NUTS!!!

**Pull request merged**
