### PR TITLE
Website

### LINKED ISSUE #238: Make a dedicated documentation website
Docusaurus looks like a good option

### PR DESCRIPTION
**Pull request by GroovinChip**
This PR contains a basic website for `macos_ui`. It was created with Docusaurus and contains a codelab for getting started with `macos_ui`. More codelabs and documentation is in progress. The website has not been deployed yet, but I have purchased the domain "macosui.dev" in preparation for deployment. I also need to figure out a logo or something, and perhaps some different images. I'm also toying with the idea of embedding the demo app into the site.

To run the website, ensure that NPM is installed. Then run `npx docusaurus start`.

Any feedback for the initial version of the website is welcome.

Closes #238 

## Pre-launch Checklist

- [ ] I have run `dartfmt` on all changed files 
- [ ] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [ ] I have added/updated relevant documentation 
- [ ] I have run "optimize/organize imports" on all changed files
- [ ] I have addressed all analyzer warnings as best I could

### CODE REVIEW

**Comment by whiplashoo** [comment]
Tried to run docusaurus start, but got this error:

```
➜  macos_ui git:(website) ✗ npx docusaurus start
  ✔ gifsicle pre-build test passed successfully
  ✔ jpegtran pre-build test passed successfully
  ✔ optipng pre-build test passed successfully
Error: No siteConfig.js file found in website folder!
```

**Comment by GroovinChip** [comment]
> Tried to run docusaurus start, but got this error:
> 
> ```
> ➜  macos_ui git:(website) ✗ npx docusaurus start
>   ✔ gifsicle pre-build test passed successfully
>   ✔ jpegtran pre-build test passed successfully
>   ✔ optipng pre-build test passed successfully
> Error: No siteConfig.js file found in website folder!
> ```

That's odd 🤔 I don't know what that's about

**Comment by GroovinChip** [comment]
> Tried to run docusaurus start, but got this error:
> 
> ```
> ➜  macos_ui git:(website) ✗ npx docusaurus start
>   ✔ gifsicle pre-build test passed successfully
>   ✔ jpegtran pre-build test passed successfully
>   ✔ optipng pre-build test passed successfully
> Error: No siteConfig.js file found in website folder!
> ```

I think you have to run `npm install` before `npx docusaurus start`

**Comment by whiplashoo** [comment]
Success! I was using an older node (and npm) version. Will have a look at the PR soon

**Review by whiplashoo — APPROVED** [review]

**Comment by GroovinChip** [comment]
@whiplashoo don't merge yet, I'm working on some more things. I'll re-request review when I'm done.

**Comment by whiplashoo** [comment]
OK, it looks really great! I like how simple and readable the tutorials are, and the interactive iframe in the front page is really nice. I will not merge, since I see that there is some cleanup necessary first.

Some quick points:

- Shouldn't syntax highlighting for code blocks work?
- Instead of the two avatar images on the home page, we could use a screenshot from the app (left) and a screenshot from a macos_ui code snippet with documentation (right).
- We could also add a hero image at the top with a Mac laptop and a macos_ui sample app in the middle of the screen. 
- I agree about having a logo (and favicon). If I come up with something, I 'll let you know.

That's from a first look, let me know and I will review your updates

**Comment by GroovinChip** [comment]
* I have no idea why the syntax highlighting doesn't work. I assume it either has something to do with the fact that turning [this](https://github.com/GroovinChip/macos_ui/blob/website/website/docusaurus.config.js#L110) on breaks the site, or the fact that it's not actually a live site (though why that would be a problem is a mystery to me)
* I like the idea of the screenshot/code sample
* Maybe instead of the hero with a Mac frame we should wrap the `iframe` in a Mac frame or something?

**Comment by GroovinChip** [comment]
@whiplashoo ok I think I'm done for now, lmk what you think of the changes. Doesn't address what we were talking about above though.

**Comment by whiplashoo** [comment]
Fixed the issue with code highlighting, and the styling of the "Check out ..." header on the home page. Site looks good! 

Maybe remove the auto-generated folders (like `blog/`) before merging? At any rate, feel free to proceed.

**Comment by GroovinChip** [comment]
Thanks! Yes, I'll continue with this either tonight or tomorrow.

I'm still stumped on what a good logo would be, any ideas?

**Comment by GroovinChip** [comment]
@whiplashoo I just pulled your changes and messing with the additional languages still breaks the site.

Screen Shot 2022-05-14 at 7 18 25 PM

**Comment by whiplashoo** [comment]
Really? I don't see an error on my end:

Screenshot 2022-05-15 at 10 08 06 AM

Maybe re-running npm install would help? FWIW, these is my node environment versions:

➜  ~ node -v
v16.7.0
➜  ~ npm -v
7.20.3

**Comment by GroovinChip** [comment]
Okay, running an `npm install` fixes the issue. Thanks!

**Comment by GroovinChip** [comment]
I'm actually going to close this in favor of pulling out the website into its own repo, so that I can deploy it with GH pages. I'm already using GH pages on this repo for the widget gallery.

**Pull request closed without merging**
