### PR TITLE
fix(docs): Remove "+" character from example

### PR DESCRIPTION
**Pull request by cbenhagen**
Most likely a copy paste leftover. Hopefully no changelog entry needed.

### CODE REVIEW

**Comment by GroovinChip** [comment]
@cbenhagen this was actually purposeful. I intended it to demonstrate that line as being highlighted as an addition, but it clearly didn't work 😅

**Comment by GroovinChip** [comment]
Kinda like [this](https://gist.github.com/salmedina/ad8bea4f46de97ea132f71b0bca73663#file-markdowndiffexample-md)

**Comment by cbenhagen** [comment]
Oh ok. Feel free to close this then. I would argue to take it out so it doesn't create a problem when copy pasting.

**Comment by GroovinChip** [comment]
Well, if you know how to make it look the way it should that would be great. Otherwise, yeah, I guess it should be removed.

**Comment by schilken** [comment]
I also just copy&pasted the Swiftcode and got this compile error:
`/macos/Runner/MainFlutterWindow.swift:32:1: error: binary operator '+' cannot be applied to operands of type 'NSRect' (aka 'CGRect') and 'NSColor?'`

I think many Flutter developers will just copy&paste the code.

Maybe wrap the '+' in a comment like /* added */ or better: just remove it. +1

**Comment by cbenhagen** [comment]
@GroovinChip why would you prefer to format this as a diff? Shouldn't the code snippet reflect the currently needed code for Flutter stable? History is always available if someone needs to see the changes that were made.

**Comment by GroovinChip** [comment]
> @GroovinChip why would you prefer to format this as a diff? Shouldn't the code snippet reflect the currently needed code for Flutter stable? History is always available if someone needs to see the changes that were made.

Yeah, that's fair.

Thank you all for setting me straight on this!

**Pull request merged**
