### PR TITLE
Allow to customize disabled background color of MacosTextField

### PR DESCRIPTION
**Pull request by nbonamy**
Allow to customize disabled background color of MacosTextField

## Pre-launch Checklist

- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

### CODE REVIEW

**Comment by GroovinChip** [comment]
@nbonamy Thanks for your contribution! Please merge in the latest changes from dev, and please post some screenshots demonstrating your change. Thank you!

**Comment by nbonamy** [comment]
Branch updated with latest dev. PR ready.

**Comment by GroovinChip** [comment]
> Branch updated with latest dev. PR ready.

Please provide a gif or screenshot of your change in action.

**Comment by GroovinChip** [comment]
@nbonamy since you've not provided a GIF or screenshot of your PR's changes, I am closing this PR. You may reopen it when you are ready to provide what I've asked for. Thanks!

**Pull request closed without merging**
